// <auto-generated />
using System;
using CMLApplication.Repository.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMLApplication.Migrations
{
    [DbContext(typeof(RepositoryDBContext))]
    [Migration("20240703144252_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMLApplication.Models.Entities.ColaboradorEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DTHR")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("IdGrupoColaborador")
                        .HasColumnType("int")
                        .HasColumnName("id_grupos_colaboradores");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("login");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultima_atualizacao");

                    b.HasKey("Id");

                    b.ToTable("colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DTHR = new DateTime(2024, 7, 3, 11, 42, 52, 163, DateTimeKind.Local).AddTicks(4840),
                            Email = "diego.santos@keyworks.com.br",
                            IdGrupoColaborador = 2,
                            Login = "str_dsantos",
                            NomeCompleto = "Diego dos Santos",
                            UltimaAtualizacao = new DateTime(2024, 7, 3, 11, 42, 52, 163, DateTimeKind.Local).AddTicks(4830)
                        });
                });

            modelBuilder.Entity("CMLApplication.Models.Entities.GrupoColaboradorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("grupos_colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Colaborador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Auditor"
                        });
                });

            modelBuilder.Entity("CMLApplication.Models.Entities.GrupoColaboradorPermissaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGrupoColaborador")
                        .HasColumnType("int")
                        .HasColumnName("id_grupos_colaboradores");

                    b.Property<int>("IdPermissao")
                        .HasColumnType("int")
                        .HasColumnName("id_permissoes");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupoColaborador");

                    b.HasIndex("IdPermissao");

                    b.ToTable("grupos_colaboradores_permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGrupoColaborador = 1,
                            IdPermissao = 1
                        },
                        new
                        {
                            Id = 2,
                            IdGrupoColaborador = 2,
                            IdPermissao = 1
                        },
                        new
                        {
                            Id = 3,
                            IdGrupoColaborador = 2,
                            IdPermissao = 2
                        },
                        new
                        {
                            Id = 4,
                            IdGrupoColaborador = 2,
                            IdPermissao = 3
                        },
                        new
                        {
                            Id = 5,
                            IdGrupoColaborador = 2,
                            IdPermissao = 4
                        },
                        new
                        {
                            Id = 6,
                            IdGrupoColaborador = 3,
                            IdPermissao = 1
                        },
                        new
                        {
                            Id = 7,
                            IdGrupoColaborador = 3,
                            IdPermissao = 2
                        },
                        new
                        {
                            Id = 8,
                            IdGrupoColaborador = 3,
                            IdPermissao = 3
                        },
                        new
                        {
                            Id = 9,
                            IdGrupoColaborador = 3,
                            IdPermissao = 4
                        });
                });

            modelBuilder.Entity("CMLApplication.Models.Entities.PermissaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Consultar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Inserir"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Atualizar"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Excluir"
                        });
                });

            modelBuilder.Entity("CMLApplication.Models.Entities.ColaboradorEntity", b =>
                {
                    b.HasOne("CMLApplication.Models.Entities.GrupoColaboradorEntity", "GrupoColaborador")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoColaborador");
                });

            modelBuilder.Entity("CMLApplication.Models.Entities.GrupoColaboradorPermissaoEntity", b =>
                {
                    b.HasOne("CMLApplication.Models.Entities.GrupoColaboradorEntity", "GrupoColaborador")
                        .WithMany()
                        .HasForeignKey("IdGrupoColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMLApplication.Models.Entities.PermissaoEntity", "Permissao")
                        .WithMany()
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoColaborador");

                    b.Navigation("Permissao");
                });
#pragma warning restore 612, 618
        }
    }
}
